### PR TITLE
Add GH actions and other GH files

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Add GH actions from the master branch.

On github I am allowed to edit your PR branch as I have write access on the original repo. But git didn't allow me to push to it. So doing it by a PR. Might be good to rebase it on your branch.

### CODE REVIEW

**Comment by alex-mitrevski** [comment]
Thanks @MatthijsBurgh!

**Comment by alex-mitrevski** [comment]
Hmm, the build fails for some reason: https://github.com/RoboCupAtHome/RuleBook/runs/5476655334?check_suite_focus=true

Any idea what the problem might be? Are the actions only defined for master perhaps?

**Comment by MatthijsBurgh** [comment]
I didn't see that we are running a local script. So that needs to be added as well.

@nickswalker is there a reason we use a local script for compiling the rulebook, but we don't use that for compiling the scoresheets?

**Comment by nickswalker** [comment]
I believe I started using that docker script to invoke the repo's makefile because it handled building the index correctly, and because the makefile defines some variables that were used in the LaTeX to stamp the PDF with the source commit hash. The scoresheets are closer to a standard set up so they build fine with a simpler action.

At least that's what my commit says: https://github.com/alex-mitrevski/RuleBook/pull/2/commits/2948ec651de3e604fd9e3fd86871f01c54db2d67

**Pull request merged**
